---
- name: Install and Configure Nginx
  hosts: Chad-RSAWEB
  become: true  # Run tasks with root privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Copy custom Nginx configuration
      template:
        src: nginx.conf.2
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted
